# Generated by Django 6.0.5 on 2026-06-09 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='city',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='company',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='relationship',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='secondary_phone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='website',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='zip_code',
        ),
    ]
